### ISSUE TITLE
Code duplicated when formatting Django HTML

### ISSUE THREAD

**Issue by lcfd** [monosans/djlint-vscode#58] opened 2022-09-07 08:40 UTC
👋 Hi, something strange is happening. 
When I use the extension to format Django HTML code the content of the file is duplicated.

I have updated DjLint and the extension.
I had to disable the automatic format and when I wanted to format I have to delete all the code generated by the duplication.

Is this a known bug?

Thank you!

**Comment by christopherpickering** [comment] 2022-09-07 11:15
Can you check if you have the latest version of djlint installed? 

There is a discord question as well, maybe it is related:

> Hey does anyone know why the formatonsave dosnt work with djlint in vscode ?

@monosans any chance you are on discord?

**Comment by lcfd** [comment] 2022-09-07 11:58
Hi, I'm not on discord but probably is the same error. Mine is more specific so it's hard to tell.

I have the latest version of DjLint.
`djlint    1.12.1`

**Comment by christopherpickering** [comment] 2022-09-07 12:51
I see the problem. I will get a new release today.

**Comment by monosans** [comment] 2022-09-07 13:53
Duplicate of https://github.com/monosans/djlint-vscode/issues/54.

@christopherpickering thanks for your help.

**Closed by monosans** 2022-09-07 13:53 UTC

**Comment by christopherpickering** [comment] 2022-09-07 14:16
Yeah, I realized the last release never made a release.

**Comment by monosans** [comment] 2022-09-07 15:06
Added a note to the README with a solution to this problem - https://github.com/monosans/djlint-vscode/commit/8996069b139e899b2ca5127527dd4ffe8460eb8b.
